---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: job-role
rules:
- apiGroups:
  - core.kubefed.io
  resources:
  - federatedtypeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patchs
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
